
---- EXPECTED OUTPUT
Fatal error: Uncaught Error: Call to undefined function foo() in %s:%d
Stack trace:
#0 [internal function]: autoload('SyntaxError')
#1 %s(%d): spl_autoload_call('SyntaxError')
#2 %s(%d): testGenerator()
#3 {main}
  thrown in %s on line %d
---- ACTUAL OUTPUT
Failed loading /opt/php-7.1/lib/php/extensions/debug-non-zts-20160303/xdebug.so:  /opt/php-7.1/lib/php/extensions/debug-non-zts-20160303/xdebug.so: cannot open shared object file: No such file or directory

Fatal error: Uncaught Error: Call to undefined function foo() in /root/php-src/Zend/tests/generators/bug65161.php:4
Stack trace:
#0 [internal function]: autoload('SyntaxError')
#1 /root/php-src/Zend/tests/generators/bug65161.php(9): spl_autoload_call('SyntaxError')
#2 /root/php-src/Zend/tests/generators/bug65161.php(13): testGenerator()
#3 {main}
  thrown in /root/php-src/Zend/tests/generators/bug65161.php on line 4
---- FAILED
