Entered try/catch
int(1)
Inner finally
Finally
Done