
---- EXPECTED OUTPUT
Fatal error: Uncaught Exception in %sbug64966.php:6
Stack trace:
#0 %sbug64966.php(13): test('iterator_apply')
#1 %sbug64966.php(18): A->b()
#2 {main}
  thrown in %sbug64966.php on line 6
---- ACTUAL OUTPUT
Failed loading /opt/php-7.1/lib/php/extensions/debug-non-zts-20160303/xdebug.so:  /opt/php-7.1/lib/php/extensions/debug-non-zts-20160303/xdebug.so: cannot open shared object file: No such file or directory

Fatal error: Uncaught Exception in /root/php-src/Zend/tests/bug64966.php:6
Stack trace:
#0 /root/php-src/Zend/tests/bug64966.php(13): test('iterator_apply')
#1 /root/php-src/Zend/tests/bug64966.php(18): A->b()
#2 {main}
  thrown in /root/php-src/Zend/tests/bug64966.php on line 6
---- FAILED
