Fatal error: Uncaught AssertionError: assert(false) in %sexception_012.php(%d) : runtime-created function:%d
Stack trace:
#0 %sexception_012.php(%d) : runtime-created function(%d): assert(false, 'assert(false)')
#1 %sexception_012.php(%d): __lambda_func()
#2 {main}
  thrown in %sexception_012.php(%d) : runtime-created function on line %d