Exception in %s:%d
Stack trace:
#0 %s(%d): Obj->__get('x')
#1 {main}
Exception in %s:%d
Stack trace:
#0 %s(%d): Obj->__get('x')
#1 {main}
Exception in %s:%d
Stack trace:
#0 %s(%d): Obj->__get('x')
#1 {main}